### ISSUE TITLE
bson extension error when running node server.js

### ISSUE THREAD

**Issue by hipitihop** [silentrob/superscript#113]
Running `node server.js` on custom server produces following error, however bot works and connects to slack. It may be a mongo issue and not specifically ss as mentioned by someone in [this thread.](https://koding.com/Activity/Post/hi-guys-i-am-getting-this-error-when-i-try-to-run-node-app-js-on-my-application)

```
node server.js
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

Environment: Ubuntu server 14.04 LTS using iojs-v2.3.0 via nvm.

**Comment by silentrob** [comment]
Superscript has not been tested extensivly on Ubuntu or IO.js. It works fine on node 0.12 so Ive assumed it would be okay in IO land. There are other native extensions, so if it was a GYP issue, nothing would work.

**Comment by espinchi** [comment]
I'm getting the same exact error message on Mac OS X 10.11.3

**Comment by jabadia** [comment]
I found this answer in stackoverflow: http://stackoverflow.com/a/28932441/79536
It worked for me
